'use strict';

const { src, dest, series, parallel, watch } = require('gulp');
const concat      = require('gulp-concat');
const uglify      = require('gulp-uglify');
const cleanCSS    = require('gulp-clean-css');
const replace     = require('gulp-replace');
const browserSync = require('browser-sync').create();
const fs   = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------
const paths = {
  templates: './src/js/views/tmpl/*.html',
  generatedTemplates: './src/js/templates.js',

  // Order matters – templates.js must come after data and before views
  scripts: [
    './src/js/data/vocabulary.js',
    './src/js/templates.js',
    './src/js/models/AppSettings.js',      // must precede all views
    './src/js/models/Flashcard.js',
    './src/js/models/FlashcardCollection.js',
    './src/js/views/MenuView.js',
    './src/js/views/VocabMenuView.js',
    './src/js/views/FlashcardView.js',
    './src/js/views/TestView.js',
    './src/js/views/SettingsView.js',
    './src/js/controllers/AppRouter.js',
    './src/js/app.js'
  ],

  styles: './src/css/app.css',
  html:   './src/index.html'
};

// ---------------------------------------------------------------------------
// clean – remove build output
// ---------------------------------------------------------------------------
function clean(cb) {
  // Remove the *contents* of build/ rather than the directory itself.
  // BrowserSync holds an open handle to the build/ directory, so deleting
  // the directory root causes EBUSY on some systems / Docker volumes.
  var buildDir = path.resolve('./build');
  if (fs.existsSync(buildDir)) {
    fs.readdirSync(buildDir).forEach(function (entry) {
      fs.rmSync(path.join(buildDir, entry), { recursive: true, force: true });
    });
  }
  cb();
}

// ---------------------------------------------------------------------------
// templates – compile *.html template files into a single templates.js
//
// Each template file becomes a property on the global `Templates` object
// keyed by filename (without extension).  Views use _.template(Templates.foo).
// ---------------------------------------------------------------------------
function templates(cb) {
  const tmplDir = path.resolve('./src/js/views/tmpl');
  const files   = fs.readdirSync(tmplDir).filter(f => f.endsWith('.html'));

  const obj = {};
  files.forEach(file => {
    const name = path.basename(file, '.html');
    obj[name]  = fs.readFileSync(path.join(tmplDir, file), 'utf8');
  });

  const content = '/* Auto-generated by gulp templates task – do not edit */\n' +
                  'var Templates = ' + JSON.stringify(obj, null, 2) + ';\n';

  fs.writeFileSync(paths.generatedTemplates, content, 'utf8');
  cb();
}

// ---------------------------------------------------------------------------
// scripts – concatenate + minify app JS into build/js/app.bundle.js
// ---------------------------------------------------------------------------
function scripts() {
  return src(paths.scripts)
    .pipe(concat('app.bundle.js'))
    .pipe(uglify())
    .pipe(dest('./build/js/'));
}

// Same as scripts but without minification (for dev)
function scriptsDev() {
  return src(paths.scripts)
    .pipe(concat('app.bundle.js'))
    .pipe(dest('./build/js/'));
}

// ---------------------------------------------------------------------------
// styles – minify CSS
// ---------------------------------------------------------------------------
function styles() {
  return src(paths.styles)
    .pipe(cleanCSS())
    .pipe(dest('./build/css/'));
}

// Same without minification
function stylesDev() {
  return src(paths.styles)
    .pipe(dest('./build/css/'));
}

// ---------------------------------------------------------------------------
// html – copy index.html to build, replacing the dev-scripts block with the
// single bundle reference so the production file is self-contained
// ---------------------------------------------------------------------------
function html() {
  return src(paths.html)
    .pipe(replace(
      /<!-- APP_SCRIPTS_START -->[\s\S]*?<!-- APP_SCRIPTS_END -->/,
      '<script src="js/app.bundle.js"></script>'
    ))
    .pipe(dest('./build/'));
}

// ---------------------------------------------------------------------------
// pwa – copy manifest.json, sw.js, and icons/ to build
// ---------------------------------------------------------------------------
function pwa() {
  return src(['./src/manifest.json', './src/sw.js', './src/icons/**/*'],
             { base: './src' })
    .pipe(dest('./build/'));
}

// ---------------------------------------------------------------------------
// Exported tasks
// ---------------------------------------------------------------------------
const build = series(clean, templates, parallel(scripts,    styles,    html,    pwa));
const dev   = series(clean, templates, parallel(scriptsDev, stylesDev, html,    pwa));

function watchFiles() {
  watch('./src/js/views/tmpl/*.html',                    series(templates, scriptsDev));
  watch(['./src/js/**/*.js', '!./src/js/templates.js'], scriptsDev);
  watch('./src/css/**/*.css',                            stylesDev);
  watch('./src/index.html',                              html);
  watch(['./src/manifest.json', './src/sw.js', './src/icons/**/*'], pwa);
}

// ---------------------------------------------------------------------------
// serve – dev build + BrowserSync server + file watching
//
// BrowserSync is configured to bind on 0.0.0.0 so it is reachable when
// running inside a Docker container with the port mapped to the host.
// ---------------------------------------------------------------------------

function bsReload(done) {
  browserSync.reload();
  done();
}

function serveTask() {
  browserSync.init({
    server:  { baseDir: './build' },
    port:    3000,
    ui:      { port: 3001 },
    host:    '0.0.0.0',    // bind all interfaces (required inside Docker)
    open:    false,         // do not auto-launch a browser
    notify:  false,
    logLevel: 'info'
  });

  // Rebuild templates + scripts when a template file changes
  watch('./src/js/views/tmpl/*.html',
    series(templates, scriptsDev, bsReload));

  // Rebuild scripts on any JS source change (excluding the generated file)
  watch(['./src/js/**/*.js', '!./src/js/templates.js'],
    series(scriptsDev, bsReload));

  // Rebuild + inject CSS (no full page reload needed)
  watch('./src/css/**/*.css', function cssRebuild() {
    return src('./src/css/app.css')
      .pipe(dest('./build/css/'))
      .pipe(browserSync.stream());   // inject CSS without reload
  });

  // Copy HTML then reload
  watch('./src/index.html', series(html, bsReload));

  // Copy PWA files then reload
  watch(['./src/manifest.json', './src/sw.js', './src/icons/**/*'],
    series(pwa, bsReload));
}

exports.templates = templates;
exports.scripts   = series(templates, scripts);
exports.styles    = styles;
exports.html      = html;
exports.pwa       = pwa;
exports.clean     = clean;
exports.dev       = dev;
exports.serve     = series(dev, serveTask);
exports.watch     = series(dev, watchFiles);
exports.build     = build;
exports.default   = build;
